- include_tasks: apt.yml
  tags:
    - apt

- include_tasks: hstr.yml
  tags:
    - hstr

- include_tasks: terraform.yml
  tags:
    - terraform

- include_tasks: terragrunt.yml
  tags:
    - terragrunt

- include_tasks: packer.yml
  tags:
    - packer

- include_tasks: terraform-docs.yml
  tags:
    - terraform-docs

- include_tasks: tflint.yml
  tags:
    - tflint
