- include_tasks: apt.yml
  tags:
    - apt

- include_tasks: terraform.yml
  tags:
    - terraform

- include_tasks: terragrunt.yml
  tags:
    - terragrunt

- include_tasks: hstr.yml
  tags:
    - hstr
