- name: Install/update pre-commit
  become: yes
  register: install
  shell:
    python3 -m pip install -U pre-commit
  changed_when: "'Collecting pre-commit' in install.stdout"
  tags:
    - pre-commit
