- name: Check vagrant version
  command: vagrant -v
  register: version
  changed_when: "version.rc != 0 or vagrant_version not in version.stdout"
  failed_when: False
  tags:
    - vagrant

- name: Install vagrant
  become: true
  when: version is changed
  unarchive:
    src: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ vagrant_binary }}.zip"
    dest: /usr/bin
    mode: "755"
    remote_src: yes
  tags:
    - vagrant
